<?php
header("Cache-Control: no cache");
session_cache_limiter("private_no_expire");
?>
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body class='container bg-dark'>

    <!-- -------------------------------------------Form --------------------------------------->

    <?php echo $this->tag->form(['index/search', 'class' => 'my-4 container text-center  p-4 border']); ?>
    <p class="row">
        <label for="email" class='label col-1 mx-5 h4 text-bold text-light'></label>
        <?php echo $this->tag->textField(['query', 'class' => 'form-control col-6']) ?>
        <?php echo $this->tag->submitButton(['Search', 'class' => 'btn  btn-primary mx-5']); ?>
    </p>
    <p class='row '>
    <div class="form-check text-light">
        <input class="form-check-input" type="checkbox" value="" id="flexCheckDefault">
        <label class="form-check-label" for="flexCheckDefault">
            Default checkbox
        </label>
    </div>
    <div class="form-check text-light">
        <input class="form-check-input" type="checkbox" value="" id="flexCheckChecked" checked>
        <label class="form-check-label" for="flexCheckChecked">
            Checked checkbox
        </label>
    </div>
    </p>
    <?php echo $this->tag->endForm(); ?>


</body>

</html>